#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 11 16:14:35 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=\u00A76[3]\u00A7d[\u5947\u5E7B]\u00A7rBliss-Shader-Unstable.zip
