#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 13 12:36:51 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=\u00A7e[2]\u00A7d[\u5947\u5E7B]\u00A7rBSL_v10.1.1 + Clrwl_1.0.5.zip
