#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 14 11:13:05 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=\u00A7e[2]\u00A7d[\u5947\u5E7B]\u00A7rComplementaryUnbound_r5.8.zip
